//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int IdEstoque { get; set; }
        public int IdCodigo { get; set; }
        public string CodBarras { get; set; }
        public string NomeProduto { get; set; }
        public string Grupo { get; set; }
        public string Curva { get; set; }
        public string Unidade { get; set; }
        public string NumeroFab { get; set; }
        public Nullable<int> EstoqueMin { get; set; }
        public Nullable<int> EstoqueMax { get; set; }
        public int EstoqueDisp { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public Nullable<decimal> Lucro { get; set; }
        public decimal Venda { get; set; }
        public Nullable<decimal> Dolar { get; set; }
        public Nullable<int> ABC { get; set; }
        public Nullable<int> Fornecedor { get; set; }
        public string Local { get; set; }
        public string Gaveta { get; set; }
        public string Utilizado { get; set; }
        public string Fabricante { get; set; }
        public string SubGrupo { get; set; }
        public string NomeCurto { get; set; }
        public string Foto { get; set; }
        public string NCM { get; set; }
        public Nullable<int> C_CST_O { get; set; }
        public Nullable<int> C_CST { get; set; }
        public Nullable<int> C_ECF_ALIQ { get; set; }
        public Nullable<int> C_ICMS { get; set; }
        public Nullable<int> C_ICMS_ST { get; set; }
        public Nullable<int> C_IPI { get; set; }
        public Nullable<int> C_RED_BCALC { get; set; }
        public Nullable<System.DateTime> DataUltVenda { get; set; }
        public Nullable<System.DateTime> DataUltCompra { get; set; }
        public Nullable<int> CFOP_INUF { get; set; }
        public Nullable<int> CFOP_OUTUF { get; set; }
        public System.DateTime DataModif { get; set; }
    }
}
