//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstoqueDivergente
    {
        public int IdEstoqueDivergente { get; set; }
        public int IdEstoque { get; set; }
        public string CodBarras { get; set; }
        public string NomeProduto { get; set; }
        public string NumeroFab { get; set; }
        public int EstoqueDisp { get; set; }
        public int EstoqueDispApurado { get; set; }
        public System.DateTime DataInclusao { get; set; }
    }
}
