//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstoqueApurado
    {
        public int IdEstoqueApurado { get; set; }
        public int EstoqueDispApurado { get; set; }
        public string CodBarrasApurado { get; set; }
        public System.DateTime DataUltModif { get; set; }
    }
}
