//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaLojaEntities : DbContext
    {
        public SistemaLojaEntities()
            : base("name=SistemaLojaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estoque> Estoques { get; set; }
        public virtual DbSet<EstoqueApurado> EstoqueApuradoes { get; set; }
        public virtual DbSet<EstoqueApuradoLog> EstoqueApuradoLogs { get; set; }
        public virtual DbSet<EstoqueDivergente> EstoqueDivergentes { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<Conta> Contas { get; set; }
        public virtual DbSet<EstoqueImpressaoEtiqueta> EstoqueImpressaoEtiquetas { get; set; }
        public virtual DbSet<SaldoInicialBanco> SaldoInicialBancoes { get; set; }
        public virtual DbSet<SubConta> SubContas { get; set; }
        public virtual DbSet<TipoConta> TipoContas { get; set; }
    
        public virtual int SalvaEstoqueDivergente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalvaEstoqueDivergente");
        }
    
        public virtual ObjectResult<SelectEstoqueSemApuracao_Result> SelectEstoqueSemApuracao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectEstoqueSemApuracao_Result>("SelectEstoqueSemApuracao");
        }
    
        public virtual int ExcluirEstoque()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExcluirEstoque");
        }
    
        public virtual ObjectResult<SelecGrupoPorCusto_Result> SelecGrupoPorCusto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelecGrupoPorCusto_Result>("SelecGrupoPorCusto");
        }
    
        public virtual ObjectResult<SelecSubGrupoPorCusto_Result> SelecSubGrupoPorCusto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelecSubGrupoPorCusto_Result>("SelecSubGrupoPorCusto");
        }
    
        public virtual ObjectResult<SelecEstoqueApuradoGrid_Result> SelecEstoqueApuradoGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelecEstoqueApuradoGrid_Result>("SelecEstoqueApuradoGrid");
        }
    
        public virtual ObjectResult<string> SelecTodasTabelas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SelecTodasTabelas");
        }
    }
}
