//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoInicialBanco
    {
        public int idSaldoInicialBanco { get; set; }
        public int idBanco { get; set; }
        public decimal ValorInicial { get; set; }
        public int Ano { get; set; }
        public System.DateTime DataModif { get; set; }
        public string Usuario { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
