//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoDeBarras
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubConta
    {
        public int idSubConta { get; set; }
        public string DescSubConta { get; set; }
        public int idConta { get; set; }
        public System.DateTime DataModif { get; set; }
        public string Usuario { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
